import {
    AlignJustifyIcon,
    BellRingIcon,
    CheckCircleIcon,
    CheckIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    CircleCheck,
    CircleXIcon,
    ClipboardIcon,
    Clock,
    CommandIcon,
    EllipsisVerticalIcon,
    ExternalLinkIcon,
    Fingerprint,
    HeadsetIcon,
    HeartIcon,
    Home,
    InfoIcon,
    LayoutGridIcon,
    Loader2Icon,
    LogOutIcon,
    LucideProps,
    Package,
    PackageOpenIcon,
    PlusCircle,
    SearchIcon,
    SettingsIcon,
    ShieldCheckIcon,
    ShoppingBagIcon,
    Trash,
    TriangleAlertIcon,
    TruckIcon,
    User,
    WalletCardsIcon,
    XIcon,
} from 'lucide-react';
import { TbShoppingCartPlus } from "react-icons/tb";
import { BsFileEarmarkPdfFill } from "react-icons/bs";

export const Icons = {
    Logo: CommandIcon,
    Home,
    Search: SearchIcon,
    Cart: ShoppingBagIcon,
    Heart: HeartIcon,
    Headset: HeadsetIcon,
    Shield: ShieldCheckIcon,
    Fingerprint,
    Truck: TruckIcon,
    PackageOpen: PackageOpenIcon,
    Loader: Loader2Icon,
    List: AlignJustifyIcon,
    Grid: LayoutGridIcon,
    Check: CheckIcon,
    X: XIcon,
    Settings: SettingsIcon,
    Logout: LogOutIcon,
    Package,
    CreditCard: WalletCardsIcon,
    Notification: BellRingIcon,
    User,
    PlusCircle,
    Trash,
    AddToCart: TbShoppingCartPlus,
    More: EllipsisVerticalIcon,
    Down: ChevronDownIcon,
    Left: ChevronLeftIcon,
    Right: ChevronRightIcon,
    Up: ChevronUpIcon,
    CircleCheck,
    Clock,
    Wallet: WalletCardsIcon,
    Copy: ClipboardIcon,
    OpenLink: ExternalLinkIcon,
    Success: CheckCircleIcon,
    Info: InfoIcon,
    Warning: TriangleAlertIcon,
    Error: CircleXIcon,
    PDF: BsFileEarmarkPdfFill
};